### ISSUE TITLE
Saving cache is skipped

### ISSUE THREAD

**Issue by cdcseacave** [lukka/run-vcpkg#171] opened 2022-11-21 13:04 UTC
Thank you for trying to make this useful action, but it does not seem to be working. At the first build attempt that failed, it cached something (as much as it built to that point), but all the following pushes on that branch do not update the incomplete cache even if the build finishes successfully. See for ex: https://github.com/cdcseacave/openMVS/actions/runs/3513334392/jobs/5886034774

Am I using it wrong or I do not understand the purpose of this action?

PS: I also noticed that the `buildtrees` and `downloads` folder are cached, which seems to me like a big waste of space (actually the build fails with run out of space error if I do not remove these folders manually every time). Why do you cache these?

**Comment by lukka** [comment] 2022-11-22 06:18
> Thank you for trying to make this useful action, but it does not seem to be working. At the first build attempt that failed, it cached something (as much as it built to that point), but all the following pushes on that branch do not update the incomplete cache even if the build finishes successfully. See for ex: https://github.com/cdcseacave/openMVS/actions/runs/3513334392/jobs/5886034774

The association between the key and the cached files is immutable, once created it won't change. You can change the key in your YAML file by prepending your custom token, or you can delete the existing cache artifact from [the github web portal](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches).

> PS: I also noticed that the `buildtrees` and `downloads` folder are cached, which seems to me like a big waste of space (actually the build fails with run out of space error if I do not remove these folders manually every time). Why do you cache these?

You are perfectly right, the `buildtrees` directory should be skipped, and unfortunately I checked now and it looks like for Linux and macOS it is not, but it does on Windows. This definitively needs a separate issue entry as that was working and it is a regression.

**Comment by cdcseacave** [comment] 2022-11-22 06:25
thank you for this solution; however I insist, is it really impossible to automatically detect that the cache changes without manually supervising it? for ex basing the cache signature on the size of the cache for instance, no of file, etc?

**Comment by lukka** [comment] 2022-11-22 15:42
@cdcseacave thanks for the suggestion! The essential part of the cache is the generation of the key, which is used to retrieve the cache before running vcpkg, or store it later after vcpkg has been run if there was a cache miss.. The key is based on various inputs that compose its sections and automatically works for most of the scenarios (e.g. vcpkg.json changed, vcpkg changed, and so on).

I'd be glad if you could expand your suggestions by creating an actionable proposal that can be applied to caching vcpkg artifacts.

**Comment by cdcseacave** [comment] 2022-11-22 16:56
the idea is not to throw away the incomplete cache, but to use it and at the end update it if required;
one practical and simple way to do this is:
1. you do not touch the key generation, it remains exactly as it is;
2. at then end when you check if the cache is already uploaded, instead of just do nothing if exists, like now, compare the number of files or their size in the cache with the value on disk; if smaller, delete the existing cache and reupload; this can be fast and easy; I imagine you know better how to store such information like number of files in the cache image or the uncompressed size; but if don't you can simply store that info in the name of the cache after the key
3. the end

**Comment by lukka** [comment] 2022-11-22 17:58
@cdcseacave great to read your suggestion, it makes sense indeed.
I have two observations:
- checking if the generated binaries (the ones going to be stored in the cache) are "complete" is only possible with a heuristic which may be not correct. This would be feasible if `vcpkg` provided a command that given a `vcpkg.json` file (which contains the definition of _what_ should be in the generated binaries) could report whether everything has already been stored in the vcpkg's binary cache. It may be an ask for the vcpkg team.
- I believe the GitHub API for the cache service were not offering a delete option when the action was written, and only recently there is a REST API that should let the action to delete an existing cache artifact. Nevertheless I cannot see a delete API in [the package which the action is using](https://www.npmjs.com/package/@actions/cache?activeTab=readme) for interacting with the GitHub cache service.

Anyone willing to give a try and implement a check for "incomplete cache" is welcome and encouraged to file a PR!

**Comment by cdcseacave** [comment] 2022-11-22 18:27
1. I don;t think you have to take care of this, vcpkg does it automatically; for ex on you machine if you press Ctrl+C at any point during vcpkg building, and restart with the same command it will know to check and resume where it needs to make sure the correct library is built
2. you do not have to delete the old cache if you can, just reupload the updated one and next time use it (use the latest one that matches the key)

**Comment by rcoup** [comment] 2022-11-24 14:40
> checking if the generated binaries (the ones going to be stored in the cache) are "complete" is only possible with a heuristic which may be not correct. This would be feasible if vcpkg provided a command that given a vcpkg.json file (which contains the definition of what should be in the generated binaries) could report whether everything has already been stored in the vcpkg's binary cache. It may be an ask for the vcpkg team.

I found this interesting bit in the [vcpkg binary caching docs](https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#implementation-notes-internal-details-subject-to-change-without-notice): 
> The hashes used are stored in the package and in the current installed directory at `/share/<port>/vcpkg_abi_info.txt`.

My first thought:
1. save SHA256 content hashes of `vcpkg/packages/<package+triplet>/share/<package>/vcpkg_abi_info.txt` in a `{<package+triplet>: <hash>}` mapping
2. after the build, get the SHA256 content hashes of `vcpkg_installed/<triplet>/share/<package>/vcpkg_abi_info.txt` and compare against the pre-build hashes
3. if there are any differences, we want to save the cache
4. the cache key could just be a sorted list of the triplet + dependency names from vcpkg.json

But: if the dependency list changes, the cache won't be restored

Maybe a per-package cache would be better? Just cache against the content hash of `vcpkg_abi_info.txt` for each package. I don't know how to get vcpkg to _pre-calculate_ the content hashes before trying to build though?

**Comment by cdcseacave** [comment] 2022-11-25 08:59
Interesting, I see your point. I do not know either if possible. However I think we over-complicate things, and usually the simplest solution even if imperfect is enough 90% time.

**Comment by rcoup** [comment] 2022-11-25 09:45
most recent thing for me was a Ninja version changing (to workaround a bug), which changed vcpkg's cache key but not the action cache key.

I'm much less worried about a few cache misses than getting in a state where builds are taking 45mins instead of 5mins 100% of the time because run-vcpkg gets a "hit" so it's never saved back again.

**Comment by rcoup** [comment] 2022-11-25 09:47
Can we tell whether vcpkg can/will/has hit the cache for everything? Then at least we can save it back if it hasn't.

**Comment by lukka** [comment] 2022-12-01 21:46
@rcoup  @cdcseacave  i am taking my time to follow up on this, I won't forget!

**Comment by lukka** [comment] 2022-12-14 08:43
@cdcseacave thanks for reporting that the cache stored on the cloud contains more data than needed (e.g. like `buildtrees` directory of vcpkg), that should be fixed in most recent `run-vcpkg@v10` version.

Regarding having a more efficient way of cache management for `run-vcpkg`, my thinking is that only vcpkg itself would be able to do a perfect job: that is, vcpkg should be the one re/storing the cache, and not the action itself.

@rcoup I like both ideas you expressed:
 - points 1 to 4 in [here](https://github.com/lukka/run-vcpkg/issues/171#issuecomment-1326540347): 
     - this idea looks like a good one to have a better heuristic for determining whether the cache should be saved or not. One problem is that the cloud cache entries are immutable, so it is not possible to save against an existent key. Whether attempting to delete an existing entry and replacing it with new content is feasible is something to be found out. As a potential example, image three workflows running altogether, all of them trying to recreate a cache entry with same key: the possible conflicts (and consequent complexity) of this scenario are never going to happen if you stick to the rule that the cache entries are immutable and can't be overwritten.
 - as well your idea of a cache entry per package: 
     - an open point is how to compute the cache key used for the restoring process.

**Comment by lukka** [comment] 2022-12-14 08:54
> Can we tell whether vcpkg can/will/has hit the cache for everything? Then at least we can save it back if it hasn't.

This is a good idea as well to determine when to save the cache. I do not have an answer though.

**Comment by rcoup** [comment] 2022-12-14 10:12
> One problem is that the cloud cache entries are immutable, so it is not possible to save against an existent key. Whether attempting to delete an existing entry and replacing it with new content is feasible is something to be found out. 

What do you mean by "cloud cache" — the GHA cache?

> As a potential example, image three workflows running altogether, all of them trying to recreate a cache entry with same key: the possible conflicts (and consequent complexity) of this scenario are never going to happen if you stick to the rule that the cache entries are immutable and can't be overwritten.

Workflows all running concurrently already clobber each other's cache entries, that's inevitable, and happens already if you push several commits requiring the (same) vcpkg rebuild. Caches are key-value stores though, so latest write "wins" — run-vcpkg/other actions don't re-read the cache entries they've written earlier in a job, so doesn't seem like a problem?

**Comment by lukka** [comment] 2022-12-14 16:01
> What do you mean by "cloud cache" — the GHA cache?

Yes, the GHA cache.

> Workflows all running concurrently already clobber each other's cache entries, that's inevitable, and happens already if you push several commits requiring the (same) vcpkg rebuild. Caches are key-value stores though, so latest write "wins" — run-vcpkg/other actions don't re-read the cache entries they've written earlier in a job, so doesn't seem like a problem?

As far as I know the first wins, as the cache is immutable by design.

**Closed** 2023-03-31 07:20 UTC
Labels: enhancement, help wanted
