### ISSUE TITLE
Warnings in caching steps

### ISSUE THREAD

**Issue by TrueBrain** [lukka/run-vcpkg#61] opened 2020-12-13 16:22 UTC
First off, I love your actions. I just wanted to have said that :D

With the new GitHub Actions Summary window, warnings are more visible. We noticed we get two warnings during cached `run-vcpkg` runs on Windows only (Mac doesn't have this issue, it seems).

1) `Warning: restoreCache() failed once: 'Error: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1' , retrying...`
Caused by:
```
  c:/vcpkg/.git/objects/pack/pack-7330effa4c511288dc38e7d7971f203d2a4a3a23.idx: Can't unlink already-existing object
  c:/vcpkg/.git/objects/pack/pack-7330effa4c511288dc38e7d7971f203d2a4a3a23.pack: Can't unlink already-existing object
```
(and this error repeats a second time)

2) `Warning: reserveCache failed: Cache already exists. Scope: refs/heads/master, Key: submodGitId=0a457099416a843f442b6c2275b2ec57239b50d9-args=-2010035955-os=1553167195-appendedKey=42-triplet=867608379, Version: e596d9224b0d5487c49893de7ad8700f61714e1ba95b948df70e6f4d9d37eb16`

Is there anything you could do to mute those warnings by any chance? :D

Cheers!

(see https://github.com/TrueBrain/OpenTTD/actions/runs/419062991 for an example of how this looks in the Summary)

**Comment by lukka** [comment] 2020-12-13 22:01
@TrueBrain thanks for reaching out! The following is what is happening:
- Once in the past, the cache has been stored successfully.
- Using the same cache key, now the restore of the existing cache partially fails (the binaries files must have been restored in `vcpkg/installed`, because the execution of `vcpkg install` tells that everything is installed already. 
 The root cause of everything is the failure of `tar` that returns exit code 1 (rather than 0) and the [@actions/cache](https://www.npmjs.com/package/@actions/cache)'s `restoreCache()` API throws an exception, then caught in [here](https://github.com/lukka/run-vcpkg/blob/main/src/vcpkg-action.ts#L94) by the `run-vcpkg` action. The latter tries again the cache restore process (this is to minimize network issues, it can be rethought).
- Now the `cacheHit` flag is set to false, hence the saving of the cache is attempted by `run-vcpkg` using an (existing) cache key. This attempt fails with a warning about that the "cache key already exists"..

Could you please activate on a run the [full log](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) so that the log contains more data to reason about?

**Comment by TrueBrain** [comment] 2020-12-13 22:14
I can do you one better: your own run also throws the error, and already has debugging on :)

https://github.com/lukka/run-vcpkg/runs/1531747501?check_suite_focus=true#step:4:106

Possibly it has been there for a while, but we never saw it; it is the new GitHub design that highlights this much more :)

If you need us to do a run, just let me know, it really is no problem. But as a developer myself, being able to reproduce issues locally always helps, hence me pointing to your own run. I am hoping that is more useful to you :)

**Comment by lukka** [comment] 2020-12-13 23:32
@TrueBrain right, I even already seen this problem in the past but totally forgot about it.

By reading various open issues, in particular [this one on the GitHub runner OS images](https://github.com/actions/virtual-environments/issues/936#issuecomment-634068778) and  [this other on @action/cache](https://github.com/actions/cache/issues/198), the solution is to change the @actions/cache's NPM package to use the GNU tar rather than the BSD one on Windows environments. And also passing in "--force-local" flag.

Whether there is anything sensible that can be done on `run-vcpkg` until this is fixed upstream, I am open to suggestions.

One potential hack is to rename the BSD `tar.exe` to anything: running the restore of the cache will then use the BSD one in the Git's bin directory. Then revert the renaming.

**Comment by TrueBrain** [comment] 2020-12-13 23:42
I like how you think :D But honestly, I do not think you should do that in your action; we can do that on the runner. Awesome, happy you found the cause of it, now we can either work around it ourself, or hope they fix it upstream soon :D Tnx!

**Comment by Shatur95** [comment] 2020-12-21 17:23
Is there a some workaround for it?

**Comment by lukka** [comment] 2020-12-22 12:36
@Shatur95 as soon a workaround is found and known to not have side effects, I would then include it in the action. 
I'd try by [prepending to the path](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path) the GNU `tar` contained in the Git's bin directory. 
I haven't yet, anyone can beat me to it and create a PR for making this change :)

**Comment by TrueBrain** [comment] 2021-01-08 09:46
When `save-cache` uses GNU `tar`, I get this error: `tar: c\:\vcpkg: Cannot stat: No such file or directory`. Not sure where the extra `\` comes from, but I guess the two tars handle manifest files differently :) Have not investigated it further.

**Comment by TrueBrain** [comment] 2021-01-08 10:37
So, instead of toying with what `tar` to use, I considered removing the problem the Windows `tar` runs into. And that seems to do the trick:

`attrib -r "c:\vcpkg\.git\*.*" /s`

It is not pretty, and for sure it has to be considered a hack. But it does remove the warning, which was the goal :D

**Comment by lukka** [comment] 2021-04-12 00:07
In the most recent run of `run-vcpkg` [functional tests](https://github.com/lukka/run-vcpkg/actions/runs/739333499) and [validation tests](https://github.com/lukka/CppBuildTasks-Validation/actions), I do not see anymore the _warning_:

 >"restoreCache() failed again: 'Error: Tar failed with error: The process 'C:\windows\System32\tar.exe' failed with exit code 1'"

which may mean it was fixed on the GitHub environment side. Nothing was changed on `run-vcpkg` to make the warning to disappear.

Let me know if this problem is still there, I am going to close this until then.

**Closed by lukka** 2021-04-12 00:07 UTC
