### ISSUE TITLE
Getting cache hit even when changing appendedCacheKey

### ISSUE THREAD

**Issue by DanEngelbrecht** [lukka/run-vcpkg#138] opened 2022-03-18 09:24 UTC
If I change appendedCacheKey between runs I still get a cache hit.

Here I changed the append key to `debug-20710ef73d32fa66a66a4fb0ed803cdce8b4099f55c53e82b7de0ec2a6fbf743-v2` for this run.
It picks up the Cache key properly `Cache key: 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69_appendedKey=debug-20710ef73d32fa66a66a4fb0ed803cdce8b4099f55c53e82b7de0ec2a6fbf743-v2'` but then it says `Cache restore keys: 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69'` and then `Cache hit, key = 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc21[24](https://github.com/EpicGames/zen/runs/5598118276?check_suite_focus=true#step:4:24)e8de991a4e45a8edcb3b4c69_appendedKey=release-20710ef73d32fa66a66a4fb0ed803cdce8b4099f55c53e82b7de0ec2a6fbf743'.` which is wrong?

Or does it deem them to be the same?

I'm running this in a private repo so sadly I can't give you access to the full build log.

```
Restore vcpkg and its artifacts from cache
  Cache key: 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69_appendedKey=debug-20710ef73d32fa66a66a4fb0ed803cdce8b4099f55c53e82b7de0ec2a6fbf743-v2'
  Cache restore keys: 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc2124e8de991a4e45a8edcb3b4c69'
  Cached paths: 'D:/a/zen/b/vcpkg_cache,D:\a\zen\zen\vcpkg,!D:\a\zen\zen\vcpkg\installed,!D:\a\zen\zen\vcpkg\vcpkg_installed,!D:\a\zen\zen\vcpkg\packages,!D:\a\zen\zen\vcpkg\buildtrees,!D:\a\zen\zen\vcpkg\downloads'
  Cache Size: ~1001 MB (1049780280 B)
  C:\Windows\System32\tar.exe -z -xf D:/a/_temp/e7d[23](https://github.com/EpicGames/zen/runs/5598118276?check_suite_focus=true#step:4:23)e4a-1f59-4550-a2e9-d05d01f2df12/cache.tgz -P -C D:/a/zen/zen
  Cache hit, key = 'runnerOS=win2220220306.1-vcpkgGitCommit=5962cf5a3bfc21[24](https://github.com/EpicGames/zen/runs/5598118276?check_suite_focus=true#step:4:24)e8de991a4e45a8edcb3b4c69_appendedKey=release-20710ef73d32fa66a66a4fb0ed803cdce8b4099f55c53e82b7de0ec2a6fbf743'.
```

The reason why I'm exploring this is because my MacOS x86_64 target does not seem to use the cache properly but instead rebuilds all dependent packages taking 1-2 hours to run.

All other platforms (Linux x86_64, Windows x86_64, MacOSX arm64) uses the cache properly - even though they show the same cache hit behaviour and do not recompile the dependencies even if I change appendedCacheKey.

**Comment by DanEngelbrecht** [comment] 2022-03-18 09:44
I *think* the reason that my MacOSX x86_64 does not use the cache properly is because it is picking up the cache that MacOSX arm64 built due to the cache fetching does not seem to respect the append key?

**Comment by lukka** [comment] 2022-03-18 11:37
@DanEngelbrecht this may be a documentation issue, something i'll take a look at soon. 

For your info, the action is optimizing the usage of the cache by using a primary and fallback (aka "restore) key(s). The latter is used to match when the primary did not match. Hence, if the primary key is a cache-miss, you can have a cache hit on the "restore keys", which includes only `runnerOS` and `vcpkgGitCommitId` (it does not include the appended value). Hence imagine you just added one package to `vcpkg.json`, you still get a cache hit on the "restore" key, and only the added package is going to be built, all the others are still coming from the cache. 
Note that in case of a cache-hit on the non-primary keys is _always_ going to publish a new cache entry with the primary key (which was missed) and restore key (which it did hit).

Regarding your exact problem, based on the explanation above, can you tell me if that makes sense, or if you still some problems? Honestly, I have not really understood what is going on in your case, but please try to re-elaborate a bit more and I am willing to help.

**Comment by DanEngelbrecht** [comment] 2022-03-18 11:52
Thanks for the swift reply @lukka.

Thanks for the explanation, I'm not sure I can get things to work with our current setup.

The basic problem is that we do not use a vcpkg.json file at all - we use the tool xmake (https://xmake.io) which uses it's own system for fetching vcpkg packages and adding a vcpkg.json causes problems.

So I basically want to cache the built dependencies "as is" from disk and I added the stuff to the appendKey in an effort to make the key unique if the dependencies were changed in the xmake config file (which includes the vcpkg dependencies).

I have tried using the built in vcpkg that comes with GitHub Actions and then just doing a brute-force caching using GitHubs own caching system but I seem unable to cache the correct folders in that case.

**Comment by DanEngelbrecht** [comment] 2022-03-18 12:34
So, I think the problem for me here is that the "restore key" does not include the architecture that is built - so I have two jobs - one MacOSX x86_64 and one MacOSX arm64 and since arch is not included the first one that posted to the fallback cache "won" and that fallback cache is pointless to the other arch.

Since building without the cache on MacOS takes 2+ hours (building the dependencies) I haven't fully tested the cycle as I did not understand how the cache keys worked until you explained it.

I'm going to try it out again and now - building twice in a row without changes and see if it picks up the primary cache.

As Github Actions have no way of clearning cache items I think it would be good to influence the restore-key as well so you can create a "fresh recovery cache".

**Comment by DanEngelbrecht** [comment] 2022-03-18 12:42
Did a new run and it does pick up the correct key which includes my arch and hash but for some reason it still rebuilds all the dependencies, don't know why.

This *only* happens on MacOS X with x86_64 arch set. MacOS X with amd64 works fine.
And GitHub Action agents all run x86_64 for Mac which makes it confusing.

**Comment by lukka** [comment] 2022-03-18 13:02
@DanEngelbrecht if I got this right, the problem is that only for `macOS x86_64` workflow the cache is restored (i.e. cache-hit), but then when vcpkg is launched, the cached artifacts are like ignored, and everything gets rebuilt from scratch.

There may be multiple reasons
- There could be something different in the environment between the workflow that creates the cache, and the one the try to consume it. The difference is so that the computation of the internal key(s), that vcpkg uses to pull from the cache, is different than the one used when the cache is created. 
- Could this be a bug in vcpkg? You could verify locally with a minimal project on a macOS x64 environment?
- depending on how vcpkg is being run, it may [pull the cache from different locations](https://vcpkg.io/en/docs/users/binarycaching.html#configuration).

Perhaps you could provide the following as attachments:
- log of a workflow that generates the cache and stored it. Would be better if there was no cache-hit.
- log of a workflow that consumed the previously generated cache (but where vcpkg had to build everything from scratch).

You may strip any non relevant portion of the logs, and please [enable debug verbose logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) before grabbing the logs.

**Comment by DanEngelbrecht** [comment] 2022-03-18 14:29
I'll see what I can come up with, but it is interesting that the MacOS arm64 and MacOS x64 run on identical machines and OS and issue the exact same instructions with the only difference being setting the architecture to x86_64.

As for "Would be better if there was no cache-hit" is hard since once a workflow is run, you will *always* get a cache hit unless you change the vcpkg git commit. 🤷

**Comment by lukka** [comment] 2022-03-21 18:01
@DanEngelbrecht i think the title of this issue is misleading, since it is actually by design. What would be a better  title that reflects the problem?

**Comment by DanEngelbrecht** [comment] 2022-06-19 22:06
Closing it since it's no longer an issue for me, switched to the standard GitHub cache Action.

**Comment by DrMcCoy** [comment] 2022-08-26 19:56
Hmm, I have a similar issue here.

The original issue I have is that a build of mine suddenly fails: https://github.com/xoreos/xoreos-tools/runs/8042356166 . It can't find "vcpkg_build_make.cmake", for some reason. The error is here: https://github.com/xoreos/xoreos-tools/runs/8042356166#step:6:121 . It previously worked fine, last on August 20. I did note that it's within the directory that is cached, though.

I forked the repo into my personal space, but there the build runs through without any problems. Both the initial run, where the cache isn't restored, and the second run, which restores the cache. So, I guess, somehow, in the xoreos space, the cache got corrupted? Maybe?

Is there a "proper" way to throw the cache away and force a miss? Because that's where I wanted to use "appendedCacheKey", to force a fresh cache. Unfortunately, with the restore key being a fallback, this doesn't work.

The workflow file in question is https://github.com/xoreos/xoreos-tools/blob/master/.github/workflows/windows_cmake_msvc.yml (that's still without the appendedCacheKey), just in case I do something fundamentally wrong in either case.

**Comment by lukka** [comment] 2022-08-27 00:33
@DrMcCoy thanks for the report!

Is this a persisting error? If so, you could verbosely listing the content of the cache during a workflow run, and see if that files is really missing. Or it may be easier I to leverage the GH CLI to list and delete existing cache entries: https://github.com/actions/gh-actions-cache#readme

Also you may bump the version to the latest on the `v10`, either by using `run-vcpkg@v10` or `run-vcpkg@v10.3`.

**Comment by DrMcCoy** [comment] 2022-08-27 08:39
> Or it may be easier I to leverage the GH CLI to list and delete existing cache entries: https://github.com/actions/gh-actions-cache#readme

Oh, this is exactly what I was looking for, thanks! And yes, with the cache delete, this error is gone.

(Of course, now it fails somewhere else, because it fails to download the boost libraries, but this also happens in my local copy too now. I guess that's a vcpkg issue. Probably because old versions got dropped and it's probably already fixed in a newer commit in vcpkg, I had that happen once already in the past.)

**Comment by akrieger** [comment] 2022-08-28 19:00
Sorry to keep revisit a closed issue, but this seems like the most relevant one.

The way run-vcpkg structures its primary and fallback keys mean that as action users, we have only two bad options for 'dumping cache' -
1) gh cli as proposed above
2) changing the vcpkg commit id
3) manually deleting anything run-vcpkg would cache before the post-workflow step.

Option 1 is painful if someone does not or has never used the gh cli. Option 2 is sometimes impossible - there may be a specific commit that must be used because other commits introduce breakages. Option 3 is difficult to 'get right' because how can you detect specific situations when you need to delete the cache?

There are multiple negative side effects to the current setup as well:
1) The binary cache being saved is potentially unbounded. Changes to the compiler hash or other environment setting would result in vcpkg rebuilding libraries and storing them in the same binary cache as previously restored, which will grow the cache without ever trimming.
2) Multiple workflows sharing the same vcpkg commit but different vcpkg.jsons will collide on restore-keys, resulting again in unwanted packages being contained within the cache and consuming excess space.
3) Any sort of cache corruption (such as an upload after a cancelled workflow that left a half-complete vcpkg install) will at best waste time as future runs will keep resuming a partial cache fill but not uploading the results, unless a rolling appended hash method is used to force a new upload eg. daily, or at worst perma-fail workloads unless a manual mitigation step from above is taken because the upload artifacts somehow cause an error with vcpkg and/or a downstream consumer. Just today I discovered that run-vcpkg will upload a new cache entry even in a cancelled workflow, with who knows what kind of intermediate state being left in the checkout.

`prependedCacheKey` would be a parallel option to `appendedCacheKey` that gives us the power to resolve all of the above with a simple commit & push, an operation that any github contributor must know how to do, and doesn't constrain them to a specific cli tool they may or may not have (or have the ability to use).

**Comment by lukka** [comment] 2022-08-28 20:34
@akrieger  thanks for the detailed explanation.
Regarding `prependedCacheKey`, that is something that certainly it can be added to `run-vcpkg`.

Additional answers here below.

 > There are multiple negative side effects to the current setup as well:
> 
> 1. The binary cache being saved is potentially unbounded. Changes to the compiler hash or other environment setting would result in vcpkg rebuilding libraries and storing them in the same binary cache as previously restored, which will grow the cache without ever trimming.

The cache will grow for a given key. Currently run-vcpkg changes the keys in several occasions:
- When the vcpkg commit id changes.
- When the vcpkg.json content changes.
- When the runner OS image changes.

Should there be another segment added to the key that may help?

> 2. Multiple workflows sharing the same vcpkg commit but different vcpkg.jsons will collide on restore-keys, resulting again in unwanted packages being contained within the cache and consuming excess space.

Would using the `vcpkg.json` content hash be an option here? I noticed in your workflow the `vcpkg.json` hash is not added to the key because there are multiple hits. You may be able to get it working by specifying:

`vcpkgJsonGlob: **/msvc-full-features/vcpkg.json`


> 3. Any sort of cache corruption (such as an upload after a cancelled workflow that left a half-complete vcpkg install) will at best waste time as future runs will keep resuming a partial cache fill but not uploading the results, unless a rolling appended hash method is used to force a new upload eg. daily, or at worst perma-fail workloads unless a manual mitigation step from above is taken because the upload artifacts somehow cause an error with vcpkg and/or a downstream consumer. Just today I discovered that run-vcpkg will upload a new cache entry even in a cancelled workflow, with who knows what kind of intermediate state being left in the checkout. https://github.com/akrieger/Cataclysm-DDA/runs/8059569828?check_suite_focus=true

Right, this is a major annoyance indeed. One workaround is provided in this https://github.com/lukka/run-vcpkg/issues/128#issuecomment-1059947725 .
My [past experiment](https://github.com/lukka/run-vcpkg/commit/c479e86c312b60938476e2c5738f242a6808cd4d) did not work in the post action as the status was always reported as "in-progress", even when the workflow was cancelled or failed. 

> `prependedCacheKey` would be a parallel option to `appendedCacheKey` that gives us the power to resolve all of the above with a simple commit & push, an operation that any github contributor must know how to do, and doesn't constrain them to a specific cli tool they may or may not have (or have the ability to use).

Yes, it makes sense to add a "prepended  cache key" input in order to get both fresh primary and restore keys.

**Comment by akrieger** [comment] 2022-08-28 20:53
So, the project I contribute to has a strict policy of maximizing approachability for new contributors and minimizing breaking changes at all costs. Because of that, all of these options:

> When the vcpkg commit id changes.
> When the vcpkg.json content changes.
> When the runner OS image changes.

almost never happen. We pick a particular known vcpkg commit and we pin our builds to it. The 'new contributor' documentation explicitly lists the same commit, so we exercise in CI exactly the workflows we guide new contributors to use, to ensure they continue to work. Raising the vcpkg commit is done only when forced - such as when portfiles refer to internet resources that are no longer available, or when critical bugs get merged into dependencies. Doing so has historically been a painful process, because many contributors are not fluent or even proficient in cli tooling and manually managing something like the vcpkg checkout.

> You may be able to get it working by specifying:

> `vcpkgJsonGlob: **/msvc-full-features/vcpkg.json`

We have two `vcpkg.json` for similar reasons as above. We have the core project which has lean dependencies (the zstd-compressed cache is ~100MB), and we have an auxiliary project that depends on the core project but also pulls in qt5, which is several hundreds of megabytes compressed and simply enormous uncompressed. It takes an inordinately long time to build and raises the bar for contribution higher. Almost no one needs to or will ever contribute to the aux project, so we gave it its own vcpkg.json file so the mandatory dependencies list stays small. That's why we manually hash the vcpkg.json files into our appendedCacheKey. But, again, the contents of the files almost never changes as I described above.

> One workaround is provided in this https://github.com/lukka/run-vcpkg/issues/128#issuecomment-1059947725 .

That relies on being able to detect 'failure'. If failure is just 'effectively total cache miss, rebuild all packages and continue', that's not detectable in any automated way.

> My [past experiment](https://github.com/lukka/run-vcpkg/commit/c479e86c312b60938476e2c5738f242a6808cd4d) did not work in the post action as the status was always reported as "in-progress", even when the workflow was cancelled or failed.

`actions/cache` somehow makes this work though. I checked and they simply use [`post-if: success()`](https://github.com/actions/cache/blob/main/action.yml#L24) in their action.yaml, whereas I see `post-if: always()` in `run-vcpkg`. I'm guessing you have a reason for it, but that means we need a knob to work around the introduced potential issues.

I'm happy that you are willing to consider `prependedCacheKey` as I think that'll let me handle all my concerns.

**Comment by akrieger** [comment] 2022-08-28 20:54
One *hilarious* workaround I just thought of is specifying vcpkg commit id as "the next git commit^", which should functionally keep the same commit in vcpkg but change then base cachekey. Assuming there's no validation on the git commit input string except that git accepts it.

**Comment by lukka** [comment] 2022-09-26 19:45
@akrieger IIRC there is a test on the commit id to represent a SHA1 string which would prevent your idea to work, which would be neat BTW. 

I think prepending the user provided key is sensible indeed, as requested as well in #160 .

**Comment by lukka** [comment] 2022-09-28 14:19
FYI a`prependedKey` input is being worked in this PR https://github.com/lukka/run-vcpkg/pull/161

**Comment by lukka** [comment] 2022-10-05 13:25
The latest version of `run-vcpkg@v10` adds the `prependedCacheKey` input, which helps in invalidating previously created caches. It also documents how to properly handle the saving of the cache when a failure and cancellation occurs.

@DanEngelbrecht  @DrMcCoy  @akrieger could this issue be closed or there is something else to do on `run-vcpkg` side? Let me know, thanks!

**Closed by lukka** 2022-10-05 13:25 UTC
