### ISSUE TITLE
logCollectionRegExps not working?

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#83] opened 2021-04-19 18:14 UTC
Using the upgraded run-vcpkg with the `logCollectionRegExps` option, it didn't seem to pick up the [build failures in this log](https://github.com/Mudlet/Mudlet/pull/5166/checks?check_run_id=2383379037#step:7:300), despite the regex matching the 1st log path:

![image](https://user-images.githubusercontent.com/110988/115283602-e0bc7b80-a14b-11eb-83fd-bfbadfd25947.png)

**Comment by lukka** [comment] 2021-04-19 21:20
@vadi2 thanks for trying this out!

I have both a [unit test](https://github.com/lukka/run-cmake-vcpkg-action-libs/blob/main/packages/action-lib/__tests__/lib.log_collection.test.ts) and a [workflow validation test](https://github.com/lukka/CppBuildTasks-Validation/runs/2372557021?check_suite_focus=true) where I have successfully exercised the "log collection" feature.

The validation test is using `CMake` to trigger an error, it would be nice to use `vcpkg` as well. How to trigger a `vcpkg` error with a log? Once we found that out, I can add it to the validation workflow and verify whether and why it is not working.

**Comment by lukka** [comment] 2021-04-19 21:29
@vadi2 by code inspection, the unit test is leveraging the wrong `ToolRunner` class, this may certainly be a problem. To be investigated.

**Comment by lukka** [comment] 2021-04-22 06:53
it turns out that the wrong `ToolRunner` used in the unit test is not the problem. It was a wrong usage of `RegExp.lastIndex` the actual root cause. I also augmented the default regular expression passed onto the `logCollectionRegExps` input. Let me know next time an error occurs whether this is working!

**Comment by vadi2** [comment] 2021-04-22 06:57
Will do!

**Comment by lukka** [comment] 2021-06-29 06:56
It should be fixed in `run-vcpkg@v7.4` or simply `run-vcpkg@v7`. Please report back!

**Closed by lukka** 2021-06-29 06:56 UTC
Labels: bug
