### ISSUE TITLE
caching is ineffective if job times out

### ISSUE THREAD

**Issue by justusranvier** [lukka/run-vcpkg#158] opened 2022-09-19 19:48 UTC
I am testing a workflow that attempts to build qtdeclarative and its dependencies for x64-windows-static.

The workflow takes a long time. So long that during the first attempt the job was automatically cancelled for taking too long:

![image](https://user-images.githubusercontent.com/1255702/191041074-be69d7b6-4d6b-4013-b0a5-417c29fe3026.png)

At the time of the cancellation it was almost done, and from the logs it was saving data to the binary cache every step of the way, however the warning in the Post Run step indicates some cache was skipped.

![image](https://user-images.githubusercontent.com/1255702/191041379-9144802e-151b-41cb-9407-5a8155d710eb.png)

Upon re-running the failed job, over a gigabyte of cache data is restored...

![image](https://user-images.githubusercontent.com/1255702/191101560-6fe6f0bb-ff0c-4d1c-8bec-13207a4baff5.png)

...but it doesn't matter because the installation starts over from the very beginning anyway, even though all packages up to qtdeclarative were built successfully and allegedly cached.

![image](https://user-images.githubusercontent.com/1255702/191101857-d9d5409d-eaa6-435b-bd80-6a9cdf869e52.png)

**Comment by lukka** [comment] 2022-09-24 20:58
@justusranvier i think as [pointed out](https://github.com/lukka/run-vcpkg/issues/128#issuecomment-1232214833) by @akrieger there is certainly some work to do on "cache saving" to support proper job cancellation.

By reading your specific problem description, in the first run no cache was saved at all, i.e. the message "Skipping cache as..." really meant "Skipping saving cache as...". Hence I wonder where the cache has been restored from, which must have been created by another prior run on the same repository and using the same cache key. Do you have an insight on this? Or do you have links to the workflow runs I can take a look at?

**Comment by justusranvier** [comment] 2022-09-26 16:54
> Hence I wonder where the cache has been restored from, which must have been created by another prior run on the same repository and using the same cache key.

That's probably what happened. I've gone through many iterations of attempting to make this work.

> Or do you have links to the workflow runs I can take a look at?

https://github.com/justusranvier/action-test/actions

**Comment by lukka** [comment] 2022-10-05 13:20
@justusranvier I looked into [this workflow run](https://github.com/justusranvier/action-test/actions/runs/3079522144/jobs/4983072048) and what happened is that the cache has been restored from a cache key containing the `runnerOS`'s version, the vcpkg Git commit id, and vcpkg.json content hash, which is the best we can get. The log also repors that vcpkg consumed 17 packages out of the content of the binary cache previously stored by some run. To proceed forward the investigation should be run by understanding what is the content of the cache at that moment, what is expected to be restored, what was consumed and what was _not_ consumed and why. 

Rather than facing this long journey, I'd verify that `run-vcpkg` is not going to be store the cache when the job is cancelled or it failed. This behavior is automatically done when using `runVcpkgInstall: true`, otherwise it is needed to drive correctly the `RUNVCPKG_NO_CACHE` environment variable as [documented](https://github.com/lukka/run-vcpkg#quickstart-with-instructions). If this behavior is not confirmed, then there is a bug in `run-vcpkg`.

Note that the cache key provided by run-vcpkg is only good approximation, but cannot cover all cases: in fact the idea of using a caching system (the one implemented in `run-vcpkg`) over the vcpkg binary cache is an ill-formed idea since the beginning.

To be perfect, the job of restoring the cache from an online service should be performed directly by vcpkg itself, as it is done with NuGet packages generated by vcpkg, and I think I will experiment with it soon.

**Comment by akrieger** [comment] 2022-10-05 17:30
> in fact the idea of using a caching system (the one implemented in run-vcpkg) over the vcpkg binary cache is an ill-formed idea since the beginning.

I mean, it'd be cool by me if `run-vcokg` only cached/restored the binary cache and nothing from the install. That's really all I wanted, I just haven't put in the time to perfectly reverse engineer 'how' to do that / where the binary cache is stored. If I did that I likely wouldn't need `run-vcpkg` but it is very convenient to keep all the logic of checking out, updating, providing, and caching vcpkg in one action.

**Comment by lukka** [comment] 2022-10-05 20:52
@akrieger the binary cache is stored in a directory, which could be set by driving the `VCPKG_DEFAULT_BINARY_CACHE ` environment variable. Saving in the cache service that directory would accomplish what you aspire. 

Could you please elaborate what benefits you would get by not caching the vcpkg data files nor the vcpkg executable? I think the latter is now not built (from sources) anymore since its already built binary is downloaded, but you still need the data files (i.e. the vcpkg repo content).

I recommend taking a look to the "pure" workflow in this C++/vcpkg/CMake repository template, which may be a ready to be used workflow you are looking for: https://github.com/lukka/CppCMakeVcpkgTemplate

**Comment by akrieger** [comment] 2022-10-05 21:09
We don't use cmake, we use visual studio/msbuild with it's native integration. The workflow runtime benefits for caching 'everything' are small compared to wins from saving the binary cache, so the increase in complexity (for me) isn't worth it if I were implementing it myself.

**Comment by lukka** [comment] 2022-10-17 04:16
@justusranvier let me know if this issue is solved with the latest version [run-vcpkg@v10.5](https://github.com/lukka/run-vcpkg/releases/tag/v10.5), closing for now, thanks!

**Closed by lukka** 2022-10-17 04:16 UTC
