### ISSUE TITLE
respect VCPKG_FORCE_SYSTEM_BINARIES

### ISSUE THREAD

**Issue by lionkor** [lukka/run-vcpkg#217] opened 2023-12-30 23:54 UTC
When VCPKG_FORCE_SYSTEM_BINARIES is set, run-vcpkg will try to build ports for both `x64` and `arm64`. The former will fail due to incompatible compiler flags.

When VCPKG_FORCE_SYSTEM_BINARIES is set, the action should assume a different default triplet than `x64`, maybe the one of the platform (like vcpkg does by default).

**Comment by lukka** [comment] 2023-12-31 08:11
@lionkor to make this request actionable I think I need your help: 
- what the problem is?
- what the observed behavior is?
- what is the expected behavior and why?

Link (or attached log to this issue) to existing failing workflows would help.

**Comment by lionkor** [comment] 2024-01-03 09:40
Sure!

## To reproduce:

1. Make a GitHub Actions workflow with `run-vcpkg` in a repo with `vcpkg.json` (manifest mode) with some dependency like `boost-system`.
2. Set `VCPKG_FORCE_SYSTEM_BINARIES: 1` in the workflow's ENV (this ensures vcpkg will build for ARM64, on ARM64).
3. Run the GitHub Actions workflow in an ARM64 runner.
4. Observe build failure due to `run-vcpkg` building for some `x64` triplet instead of just the arm64 triplet.

## The problem:

VCPKG_FORCE_SYSTEM_BINARIES means that vcpkg should ONLY build for the target triplet, not some cross-compilation triplet, in this case.

## The observed behavior:

Build failure on arm64.

## Logs:

https://pastebin.com/rvGhAdF0

The paste includes ONLY the `run-vcpkg` invokation,  for your convenience, because the rest of the log is huge. You can see the VCPKG_FORCE_SYSTEM_BINARIES in the env for that run.

Please observe line **345** in this log for the incorrect detection of `x64` as described above.
Observe also line **786** where the arm64 gcc compiler obviously fails to build with x64 flags (because it does not support those flags, because they're specific to x64 afaik).

## Expected behavior:

When running vcpkg in a bare-metal arm64 machine, with ONLY the `VCPKG_FORCE_SYSTEM_BINARIES=1` set, vcpkg in manifest mode will correctly only build the arm64 builds as you can see in this log: https://pastebin.com/mT5V8ZNP

**Comment by lionkor** [comment] 2024-01-03 09:41
Here's a link to the actual workflow file, before hotfixing it by setting the triplet (which is NOT needed since the `run-vcpkg` action runs on arm64 itself and vcpkg knows it's arm64: https://github.com/BeamMP/BeamMP-Server/actions/runs/7366964699/workflow

**Comment by lukka** [comment] 2024-01-03 12:29
@lionkor thank you for a throughout explanation of the problem!
It is indeed a `run-vcpkg` issue, the [getDefaultTriplet](https://github.com/lukka/run-cmake-vcpkg-action-libs/blob/b0df4e36c217661af4b1261558201d2cc5e1dc70/packages/base-util-lib/src/base-util-lib.ts#L133) needs to be augmented to be able to tell whether the default vcpkg triplet is for Intel or ARM based CPUs.
The [RUNNER_ARCH](https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables) environment variable could be used to detect ARM vs Intel platforms, and if it is not set, the fallback would be [os.arch()](https://nodejs.org/api/os.html#osarch), which is not perfect as it reports the target platform of the nodejs executable, but it is good most of the times.

**Comment by lionkor** [comment] 2024-01-04 09:36
Wonderful, thank you!
Let me know if you need anything else, I have runners and arm64 machines to test with.

**Comment by lukka** [comment] 2024-01-05 08:23
@lionkor you may try the `run-vcpkg@dev/arm-triplet-fix` which contains the proposed fix. Let me know if this is working for you as well!

**Comment by lionkor** [comment] 2024-01-09 14:40
Thank you very much, looks sane to me. Will test when I get a chance & get back to you

**Comment by lukka** [comment] 2024-02-11 16:21
@lionkor I proceeded forward and released a new version of `run-vcpkg@v11.5` with the fix merged in. Let me know if it works for you, thank you.

**Closed by lukka** 2024-02-11 16:21 UTC
