### ISSUE TITLE
Hard Crash (SigSegv?) After Warning 

### ISSUE THREAD

**Issue by sysnet-ai** [lukka/run-vcpkg#88] opened 2021-07-21 18:55 UTC
I have a job that last time it finished successfully it had a warning:
```
build (3.8, windows-latest)
restoreCache() failed once: 'Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close' 
```

Since then all runs have failed because vcpkg seems to SIGSEGV:
```
scons: Reading SConscript files ...
Getting Dependencies: 
D:\a\sidecar\sidecar\vcpkg/vcpkg install --x-install-root=./vcpkg_installed --triplet=x64-windows --overlay-triplets=./triplet-overlays/
CompletedProcess(args=['D:\\a\\sidecar\\sidecar\\vcpkg/vcpkg', 'install', '--x-install-root=./vcpkg_installed', '--triplet=x64-windows', '--overlay-triplets=./triplet-overlays/'], returncode=3221225477, stdout=b'', stderr=b'')
```

A python (Scons) script runs the command and as you can see there's no stdout or stderr, it just spits out `3221225477` as return code. Which seems to be SEGFAULT from cursory search.
The build then fails because it can't find the dependencies.

Jobs from other branches seem to be successful, but any branches created from this one get the same behavior.
I tried changing `vcpkg.json` to see if I could trigger a cache invalidation, but didn't seem to work.

Unfortunately this is happening in a private repository so I cannot share the job directly.
But we appreciate any potential help or pointers on how to further triage.

### Output of failing job - Setup Step:
```
Run lukka/run-vcpkg@v7
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\sidecar\sidecar\vcpkg' ...
bd2d86198978ee35fe9aadde3b0f7487f536fbe7
vcpkg identified at commitId='bd2d86198978ee35fe9aadde3b0f7487f536fbe7', adding it to the cache's key.
Cache's key = 'localGitId=-574880384-args=42-os=1553167250-imageVer=-2107304870-appendedKey=2045662659-triplet=1258145250'.
Restore vcpkg and its artifacts from cache
  Cache's key = 'localGitId=-574880384-args=42-os=1553167250-imageVer=-2107304870-appendedKey=2045662659-triplet=1258145250', paths = 'D:\a\sidecar\sidecar\vcpkg,!D:\a\sidecar\sidecar\vcpkg\packages,!D:\a\sidecar\sidecar\vcpkg\buildtrees,!D:\a\sidecar\sidecar\vcpkg\downloads,D:\a\sidecar\sidecar/clients/cpp/vcpkg_installed'
  Running restore-cache...
  Cache miss.
⏱ elapsed: 0.364 seconds
Set output env vars
  Set the output variable 'RUNVCPKG_VCPKG_ROOT_OUT' to value: D:\a\sidecar\sidecar\vcpkg
  Set the environment variable 'RUNVCPKG_VCPKG_TRIPLET' to value: x64-windows
  Set the output variable 'RUNVCPKG_VCPKG_TRIPLET_OUT' to value: x64-windows
⏱ elapsed: 0.002 seconds
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\sidecar\sidecar\vcpkg' ...
bd2d86198978ee35fe9aadde3b0f7487f536fbe7
Check whether vcpkg repository is up to date
⏱ elapsed: 0.571 seconds
Download vcpkg source code repository
⏱ elapsed: 6.703 seconds
Build vcpkg
⏱ elapsed: 0.987 seconds
Prepare vcpkg generated file for caching
⏱ elapsed: 0.000 seconds
run-vcpkg action execution succeeded
```

### Output of last succeeding job - Setup Step - Here is where we see the Warning:
```
Run lukka/run-vcpkg@v7
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\sidecar\sidecar\vcpkg' ...
90b0a50e3b7c0ce7bfce14325a2c9d0759f2bbe7
vcpkg identified at commitId='90b0a50e3b7c0ce7bfce14325a2c9d0759f2bbe7', adding it to the cache's key.
Cache's key = 'localGitId=-574880384-args=42-os=1553167250-imageVer=-2107296685-appendedKey=-1364181334-triplet=1258145250'.
Restore vcpkg and its artifacts from cache
  Cache's key = 'localGitId=-574880384-args=42-os=1553167250-imageVer=-2107296685-appendedKey=-1364181334-triplet=1258145250', paths = 'D:\a\sidecar\sidecar\vcpkg,!D:\a\sidecar\sidecar\vcpkg\packages,!D:\a\sidecar\sidecar\vcpkg\buildtrees,!D:\a\sidecar\sidecar\vcpkg\downloads,D:\a\sidecar\sidecar/clients/cpp/vcpkg_installed'
  Running restore-cache...
  Warning: restoreCache() failed once: 'Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close' , retrying...
  Cache Size: ~558 MB (584804107 B)
  C:\Windows\System32\tar.exe -z -xf D:/a/_temp/a09745f1-bc57-4396-a9a0-3fc857b349ae/cache.tgz -P -C D:/a/sidecar/sidecar
  Cache hit, id=localGitId=-574880384-args=42-os=1553167250-imageVer=-2107296685-appendedKey=-1364181334-triplet=1258145250.
⏱ elapsed: 52.227 seconds
Set output env vars
⏱ elapsed: 0.543 seconds
tool: C:\Program Files\Git\bin\git.exe
Fetching the Git commit id at 'D:\a\sidecar\sidecar\vcpkg' ...
9172179c513aa84308e48b8dd0e3df90acec7204
Check whether vcpkg repository is up to date
⏱ elapsed: 0.407 seconds
Check whether last vcpkg's build is up to date with sources
⏱ elapsed: 0.000 seconds
Check vcpkg executable exists
⏱ elapsed: 1.500 seconds
Prepare vcpkg generated file for caching
⏱ elapsed: 0.001 seconds
run-vcpkg action execution succeeded
```

### Build Step:
```
scons: Reading SConscript files ...
Getting Dependencies: 
D:\a\sidecar\sidecar\vcpkg/vcpkg install --x-install-root=./vcpkg_installed --triplet=x64-windows --overlay-triplets=./triplet-overlays/
Detecting compiler hash for triplet x64-windows...
All requested packages are currently installed.

Total elapsed time: 13.5 us
```

### Post Build Step:
```
Post job cleanup.
Save vcpkg and its artifacts to cache
  Cache hit occurred on the cache key 'localGitId=-574880384-args=42-os=1553167250-imageVer=-2107296685-appendedKey=-1364181334-triplet=1258145250', saving cache is skipped.
⏱ elapsed: 0.131 seconds
run-vcpkg post action execution succeeded
```

**Comment by jwillemsen** [comment] 2021-07-22 06:20
We have also run-vcpkg issues since yesterday, see https://github.com/DOCGroup/ACE_TAO/pull/1627 and https://github.com/DOCGroup/ACE_TAO/pull/1627/checks?check_run_id=3131169592 we get

```
Error: Last command execution failed with error code '3221225477'.
    at BaseUtilLib.throwIfErrorCode (D:\a\_actions\lukka\run-vcpkg\v7\dist\index.js:4920:19)
    at VcpkgRunner.<anonymous> (D:\a\_actions\lukka\run-vcpkg\v7\dist\index.js:5702:28)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-vcpkg\v7\dist\index.js:5511:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: run-vcpkg action execution failed: Error: Last command execution failed with error code '3221225477'.
```

**Comment by jwillemsen** [comment] 2021-07-22 07:09
My PR https://github.com/lukka/run-vcpkg/pull/89 to enable the github action CI on a schedule and manual does exhibit the same problem

**Comment by jwillemsen** [comment] 2021-07-22 12:34
A downgrade to v6 doesn't work as temporary workaround (see https://github.com/DOCGroup/ACE_TAO/pull/1629)

**Comment by lukka** [comment] 2021-07-22 13:18
@sysnet-ai @jwillemsen  thanks for the report! It looks like the cause may be the recent update to GitHub Environments, notably the [update 20210719.0](https://github.com/actions/virtual-environments/releases).

I run the whole set of validation workflows, and only [one failed](https://github.com/lukka/CppBuildTasks-Validation/runs/3133689625?check_suite_focus=true) exactly as you described, while computing the plan:

```
Computing installation plan...
##[debug]Exit code '3221225477' received from command '"D:\a\CppBuildTasks-Validation\b\vcpkg\vcpkg.exe"'
  ##[debug]STDIO streams have closed for command '"D:\a\CppBuildTasks-Validation\b\vcpkg\vcpkg.exe"'
  Error: Last command execution failed with error code '3221225477'.
  ::endgroup::
⏱ elapsed: 2.352 seconds
```

The other workflows did not fail though, and they use same commit id of `vcpkg` as well same build environment.

Notes:
- caching is not the issue, as the problem is exposed when the cache is missed.
- the problem happens while vcpkg.exe is running and failing with error `3221225477` while computing the installation plan. 

**Ask:**
I think it could help to get more data, if anyone could provide the output of a failing workflow with [verbose debug output enabled](https://docs.github.com/en/actions/managing-workflow-runs/enabling-debug-logging) it could shed some light.

Suggestions that could help to workaround the problem:
- using a different environment.
- using a different `vcpkg` commit id.

**Comment by lukka** [comment] 2021-07-23 11:16
@sysnet-ai  @jwillemsen this is the root cause of this issue: https://gitlab.kitware.com/cmake/cmake/-/issues/22371

**Comment by lukka** [comment] 2021-07-23 16:33
Solutions:
- if you want to keep using the existing `vcpkg` set of libraries: since the problem is in `CMake` `v3.21`, let's use previous version `v3.20`, and switch to `CMake` `v3.21.x` whenever this problem is fixed on **CMake** as well. E.g., before invoking `run-vcpkg` invoke `uses: lukka/get-cmake@v3.20.1`
-  upgrade to most recent `vcpkg`, which works around the problem, e.g. `8ad95bc1626d4caa857cfde7c0d7c70b76fe8f74` or more recent commit id.

**Comment by Shatur** [comment] 2021-07-23 16:40
> upgrade to most recent vcpkg, which works around the problem, e.g. 8ad95bc1626d4caa857cfde7c0d7c70b76fe8f74 or more recent commit id.

There is no such commit. Maybe you meant 8b1c04b3b8e50db93d0245e761f3d8ebeb400309?

**Comment by lukka** [comment] 2021-07-23 16:51
@Shatur right! I fixed the exact commit id in the comment. Note that the commit id must belong to the `vcpkg` repo (not to `vcpkg-tool`), and i am not even sure where I got the original one I mentioned either...

**Comment by jwillemsen** [comment] 2021-07-23 17:02
Thanks! Making some PRs to upgrade to d417ae59d6e9aa20d9f812b5deb966645c54687d

**Closed** 2021-07-23 18:10 UTC
